name: Security Checks

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test --if-present

      - name: Run security lint
        run: npm run lint:security --if-present

      - name: Check package vulnerabilities
        run: npm audit --audit-level=moderate || true

      - name: Scan for secrets
        uses: gitleaks/gitleaks-action@v2
        with:
          args: "--no-git -v"

      - name: Upload gitleaks report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks.*.json
          if-no-files-found: ignore

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
